/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSTRUCOES = 5;
  /** RegularExpression Id. */
  int INSTRUCAO_THEN = 6;
  /** RegularExpression Id. */
  int INSTRUCAO_DO = 7;
  /** RegularExpression Id. */
  int FUNCOES = 8;
  /** RegularExpression Id. */
  int COMANDOS = 9;
  /** RegularExpression Id. */
  int PALAVRAS_RESERVADAS = 10;
  /** RegularExpression Id. */
  int OPERADORES = 11;
  /** RegularExpression Id. */
  int COMPARADORES = 12;
  /** RegularExpression Id. */
  int TIPOS = 13;
  /** RegularExpression Id. */
  int BOOLEANAS = 14;
  /** RegularExpression Id. */
  int NUMEROS = 15;
  /** RegularExpression Id. */
  int SIMBOLOS_ESPECIAIS = 16;
  /** RegularExpression Id. */
  int IDENTIFICADORES = 17;
  /** RegularExpression Id. */
  int PROGRAMA = 18;
  /** RegularExpression Id. */
  int ABRE_PARENTESE = 19;
  /** RegularExpression Id. */
  int FECHA_PARENTESE = 20;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 21;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 22;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 23;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 24;
  /** RegularExpression Id. */
  int SIMBOLOS = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<INSTRUCOES>",
    "\"then\"",
    "\"do\"",
    "<FUNCOES>",
    "<COMANDOS>",
    "<PALAVRAS_RESERVADAS>",
    "<OPERADORES>",
    "<COMPARADORES>",
    "<TIPOS>",
    "<BOOLEANAS>",
    "<NUMEROS>",
    "<SIMBOLOS_ESPECIAIS>",
    "<IDENTIFICADORES>",
    "\"Program \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<SIMBOLOS>",
  };

}
